# -*- coding: utf-8 -*-

from django.conf import settings
if settings.DATABASE_ENGINE == 'mysql':
    from dmigrations.mysql import migrations as m
elif settings.DATABASE_ENGINE == 'sqlite3':
    from dmigrations.sqlite3 import migrations as m

class CustomMigration(m.Migration):
    def __init__(self):
        sql_up = ['delete from places_country',
'insert into places_country (country_code, name) values ("AF","Afghanistan")',
'insert into places_country (country_code, name) values ("AX","Åland Islands")',
'insert into places_country (country_code, name) values ("AL","Albania")',
'insert into places_country (country_code, name) values ("DZ","Algeria")',
'insert into places_country (country_code, name) values ("AS","American Samoa")',
'insert into places_country (country_code, name) values ("AD","Andorra")',
'insert into places_country (country_code, name) values ("AO","Angola")',
'insert into places_country (country_code, name) values ("AI","Anguilla")',
'insert into places_country (country_code, name) values ("AQ","Antarctica")',
'insert into places_country (country_code, name) values ("AG","Antigua and Barbuda")',
'insert into places_country (country_code, name) values ("AR","Argentina")',
'insert into places_country (country_code, name) values ("AM","Armenia")',
'insert into places_country (country_code, name) values ("AW","Aruba")',
'insert into places_country (country_code, name) values ("AU","Australia")',
'insert into places_country (country_code, name) values ("AT","Austria")',
'insert into places_country (country_code, name) values ("AZ","Azerbaijan")',
'insert into places_country (country_code, name) values ("BS","Bahamas")',
'insert into places_country (country_code, name) values ("BH","Bahrain")',
'insert into places_country (country_code, name) values ("BD","Bangladesh")',
'insert into places_country (country_code, name) values ("BB","Barbados")',
'insert into places_country (country_code, name) values ("BY","Belarus")',
'insert into places_country (country_code, name) values ("BE","Belgium")',
'insert into places_country (country_code, name) values ("BZ","Belize")',
'insert into places_country (country_code, name) values ("BJ","Benin")',
'insert into places_country (country_code, name) values ("BM","Bermuda")',
'insert into places_country (country_code, name) values ("BT","Bhutan")',
'insert into places_country (country_code, name) values ("BO","Bolivia")',
'insert into places_country (country_code, name) values ("BA","Bosnia and Herzegovina")',
'insert into places_country (country_code, name) values ("BW","Botswana")',
'insert into places_country (country_code, name) values ("BV","Bouvet Island")',
'insert into places_country (country_code, name) values ("BR","Brazil")',
'insert into places_country (country_code, name) values ("IO","British Indian Ocean Territory")',
'insert into places_country (country_code, name) values ("VG","British Virgin Islands")',
'insert into places_country (country_code, name) values ("BN","Brunei")',
'insert into places_country (country_code, name) values ("BG","Bulgaria")',
'insert into places_country (country_code, name) values ("BF","Burkina Faso")',
'insert into places_country (country_code, name) values ("BI","Burundi")',
'insert into places_country (country_code, name) values ("KH","Cambodia")',
'insert into places_country (country_code, name) values ("CM","Cameroon")',
'insert into places_country (country_code, name) values ("CA","Canada")',
'insert into places_country (country_code, name) values ("CV","Cape Verde")',
'insert into places_country (country_code, name) values ("KY","Cayman Islands")',
'insert into places_country (country_code, name) values ("CF","Central African Republic")',
'insert into places_country (country_code, name) values ("TD","Chad")',
'insert into places_country (country_code, name) values ("CL","Chile")',
'insert into places_country (country_code, name) values ("CN","China")',
'insert into places_country (country_code, name) values ("CX","Christmas Island")',
'insert into places_country (country_code, name) values ("CC","Cocos (Keeling) Islands")',
'insert into places_country (country_code, name) values ("CO","Colombia")',
'insert into places_country (country_code, name) values ("KM","Comoros")',
'insert into places_country (country_code, name) values ("CG","Congo")',
'insert into places_country (country_code, name) values ("CK","Cook Islands")',
'insert into places_country (country_code, name) values ("CR","Costa Rica")',
'insert into places_country (country_code, name) values ("CI","Côte d\'Ivoire")',
'insert into places_country (country_code, name) values ("HR","Croatia")',
'insert into places_country (country_code, name) values ("CU","Cuba")',
'insert into places_country (country_code, name) values ("CY","Cyprus")',
'insert into places_country (country_code, name) values ("CZ","Czech Republic")',
'insert into places_country (country_code, name) values ("CD","Democratic Republic of the Congo")',
'insert into places_country (country_code, name) values ("DK","Denmark")',
'insert into places_country (country_code, name) values ("DJ","Djibouti")',
'insert into places_country (country_code, name) values ("DM","Dominica")',
'insert into places_country (country_code, name) values ("DO","Dominican Republic")',
'insert into places_country (country_code, name) values ("TL","East Timor")',
'insert into places_country (country_code, name) values ("EC","Ecuador")',
'insert into places_country (country_code, name) values ("EG","Egypt")',
'insert into places_country (country_code, name) values ("SV","El Salvador")',
'insert into places_country (country_code, name) values ("GQ","Equatorial Guinea")',
'insert into places_country (country_code, name) values ("ER","Eritrea")',
'insert into places_country (country_code, name) values ("EE","Estonia")',
'insert into places_country (country_code, name) values ("ET","Ethiopia")',
'insert into places_country (country_code, name) values ("FK","Falkland Islands")',
'insert into places_country (country_code, name) values ("FO","Faroe Islands")',
'insert into places_country (country_code, name) values ("FM","Federated States of Micronesia")',
'insert into places_country (country_code, name) values ("FJ","Fiji")',
'insert into places_country (country_code, name) values ("FI","Finland")',
'insert into places_country (country_code, name) values ("FR","France")',
'insert into places_country (country_code, name) values ("GF","French Guiana")',
'insert into places_country (country_code, name) values ("PF","French Polynesia")',
'insert into places_country (country_code, name) values ("TF","French Southern Territories")',
'insert into places_country (country_code, name) values ("GA","Gabon")',
'insert into places_country (country_code, name) values ("GM","Gambia")',
'insert into places_country (country_code, name) values ("GE","Georgia")',
'insert into places_country (country_code, name) values ("DE","Germany")',
'insert into places_country (country_code, name) values ("GH","Ghana")',
'insert into places_country (country_code, name) values ("GI","Gibraltar")',
'insert into places_country (country_code, name) values ("GR","Greece")',
'insert into places_country (country_code, name) values ("GL","Greenland")',
'insert into places_country (country_code, name) values ("GD","Grenada")',
'insert into places_country (country_code, name) values ("GG","Guernsey")',
'insert into places_country (country_code, name) values ("GP","Guadeloupe")',
'insert into places_country (country_code, name) values ("GU","Guam")',
'insert into places_country (country_code, name) values ("GT","Guatemala")',
'insert into places_country (country_code, name) values ("GW","Guinea-Bissau")',
'insert into places_country (country_code, name) values ("GN","Guinea")',
'insert into places_country (country_code, name) values ("GY","Guyana")',
'insert into places_country (country_code, name) values ("HT","Haiti")',
'insert into places_country (country_code, name) values ("HM","Heard Island and McDonald Islands")',
'insert into places_country (country_code, name) values ("HN","Honduras")',
'insert into places_country (country_code, name) values ("HK","Hong Kong")',
'insert into places_country (country_code, name) values ("HU","Hungary")',
'insert into places_country (country_code, name) values ("IS","Iceland")',
'insert into places_country (country_code, name) values ("IN","India")',
'insert into places_country (country_code, name) values ("ID","Indonesia")',
'insert into places_country (country_code, name) values ("IR","Iran")',
'insert into places_country (country_code, name) values ("IQ","Iraq")',
'insert into places_country (country_code, name) values ("IE","Ireland")',
'insert into places_country (country_code, name) values ("IL","Israel")',
'insert into places_country (country_code, name) values ("IM","Isle of Man")',
'insert into places_country (country_code, name) values ("IT","Italy")',
'insert into places_country (country_code, name) values ("JE","Jersey")',
'insert into places_country (country_code, name) values ("JM","Jamaica")',
'insert into places_country (country_code, name) values ("JP","Japan")',
'insert into places_country (country_code, name) values ("JO","Jordan")',
'insert into places_country (country_code, name) values ("KZ","Kazakhstan")',
'insert into places_country (country_code, name) values ("KE","Kenya")',
'insert into places_country (country_code, name) values ("KI","Kiribati")',
'insert into places_country (country_code, name) values ("KW","Kuwait")',
'insert into places_country (country_code, name) values ("KG","Kyrgyzstan")',
'insert into places_country (country_code, name) values ("LA","Laos")',
'insert into places_country (country_code, name) values ("LV","Latvia")',
'insert into places_country (country_code, name) values ("LB","Lebanon")',
'insert into places_country (country_code, name) values ("LS","Lesotho")',
'insert into places_country (country_code, name) values ("LR","Liberia")',
'insert into places_country (country_code, name) values ("LY","Libya")',
'insert into places_country (country_code, name) values ("LI","Liechtenstein")',
'insert into places_country (country_code, name) values ("LT","Lithuania")',
'insert into places_country (country_code, name) values ("LU","Luxembourg")',
'insert into places_country (country_code, name) values ("MO","Macao")',
'insert into places_country (country_code, name) values ("MG","Madagascar")',
'insert into places_country (country_code, name) values ("MW","Malawi")',
'insert into places_country (country_code, name) values ("MY","Malaysia")',
'insert into places_country (country_code, name) values ("MV","Maldives")',
'insert into places_country (country_code, name) values ("ML","Mali")',
'insert into places_country (country_code, name) values ("MT","Malta")',
'insert into places_country (country_code, name) values ("MH","Marshall Islands")',
'insert into places_country (country_code, name) values ("MQ","Martinique")',
'insert into places_country (country_code, name) values ("MR","Mauritania")',
'insert into places_country (country_code, name) values ("MU","Mauritius")',
'insert into places_country (country_code, name) values ("YT","Mayotte")',
'insert into places_country (country_code, name) values ("MX","Mexico")',
'insert into places_country (country_code, name) values ("MD","Moldova")',
'insert into places_country (country_code, name) values ("MC","Monaco")',
'insert into places_country (country_code, name) values ("MN","Mongolia")',
'insert into places_country (country_code, name) values ("MS","Montserrat")',
'insert into places_country (country_code, name) values ("MA","Morocco")',
'insert into places_country (country_code, name) values ("MZ","Mozambique")',
'insert into places_country (country_code, name) values ("MM","Myanmar")',
'insert into places_country (country_code, name) values ("NA","Namibia")',
'insert into places_country (country_code, name) values ("NR","Nauru")',
'insert into places_country (country_code, name) values ("NP","Nepal")',
'insert into places_country (country_code, name) values ("NL","Netherlands")',
'insert into places_country (country_code, name) values ("AN","Netherlands Antilles")',
'insert into places_country (country_code, name) values ("NC","New Caledonia")',
'insert into places_country (country_code, name) values ("NZ","New Zealand")',
'insert into places_country (country_code, name) values ("NI","Nicaragua")',
'insert into places_country (country_code, name) values ("NG","Nigeria")',
'insert into places_country (country_code, name) values ("NE","Niger")',
'insert into places_country (country_code, name) values ("NU","Niue")',
'insert into places_country (country_code, name) values ("NF","Norfolk Island")',
'insert into places_country (country_code, name) values ("KP","North Korea")',
'insert into places_country (country_code, name) values ("MP","Northern Mariana Islands")',
'insert into places_country (country_code, name) values ("NO","Norway")',
'insert into places_country (country_code, name) values ("OM","Oman")',
'insert into places_country (country_code, name) values ("PK","Pakistan")',
'insert into places_country (country_code, name) values ("PW","Palau")',
'insert into places_country (country_code, name) values ("PS","Palestinian Territories")',
'insert into places_country (country_code, name) values ("PA","Panama")',
'insert into places_country (country_code, name) values ("PG","Papua New Guinea")',
'insert into places_country (country_code, name) values ("PY","Paraguay")',
'insert into places_country (country_code, name) values ("PE","Peru")',
'insert into places_country (country_code, name) values ("PH","Philippines")',
'insert into places_country (country_code, name) values ("PN","Pitcairn Islands")',
'insert into places_country (country_code, name) values ("PL","Poland")',
'insert into places_country (country_code, name) values ("PT","Portugal")',
'insert into places_country (country_code, name) values ("PR","Puerto Rico")',
'insert into places_country (country_code, name) values ("QA","Qatar")',
'insert into places_country (country_code, name) values ("RE","Réunion")',
'insert into places_country (country_code, name) values ("MK","Republic of Macedonia")',
'insert into places_country (country_code, name) values ("RO","Romania")',
'insert into places_country (country_code, name) values ("RU","Russia")',
'insert into places_country (country_code, name) values ("RW","Rwanda")',
'insert into places_country (country_code, name) values ("SH","Saint Helena")',
'insert into places_country (country_code, name) values ("KN","Saint Kitts and Nevis")',
'insert into places_country (country_code, name) values ("LC","Saint Lucia")',
'insert into places_country (country_code, name) values ("PM","Saint-Pierre and Miquelon")',
'insert into places_country (country_code, name) values ("VC","Saint Vincent and the Grenadines")',
'insert into places_country (country_code, name) values ("WS","Samoa")',
'insert into places_country (country_code, name) values ("SM","San Marino")',
'insert into places_country (country_code, name) values ("ST","São Tomé and Príncipe")',
'insert into places_country (country_code, name) values ("SA","Saudi Arabia")',
'insert into places_country (country_code, name) values ("SN","Senegal")',
'insert into places_country (country_code, name) values ("CS","Serbia and Montenegro")',
'insert into places_country (country_code, name) values ("SC","Seychelles")',
'insert into places_country (country_code, name) values ("SL","Sierra Leone")',
'insert into places_country (country_code, name) values ("SG","Singapore")',
'insert into places_country (country_code, name) values ("SK","Slovakia")',
'insert into places_country (country_code, name) values ("SI","Slovenia")',
'insert into places_country (country_code, name) values ("SB","Solomon Islands")',
'insert into places_country (country_code, name) values ("SO","Somalia")',
'insert into places_country (country_code, name) values ("ZA","South Africa")',
'insert into places_country (country_code, name) values ("GS","South Georgia and the South Sandwich Islands")',
'insert into places_country (country_code, name) values ("KR","South Korea")',
'insert into places_country (country_code, name) values ("ES","Spain")',
'insert into places_country (country_code, name) values ("LK","Sri Lanka")',
'insert into places_country (country_code, name) values ("SD","Sudan")',
'insert into places_country (country_code, name) values ("SR","Suriname")',
'insert into places_country (country_code, name) values ("SJ","Svalbard")',
'insert into places_country (country_code, name) values ("SZ","Swaziland")',
'insert into places_country (country_code, name) values ("SE","Sweden")',
'insert into places_country (country_code, name) values ("CH","Switzerland")',
'insert into places_country (country_code, name) values ("SY","Syria")',
'insert into places_country (country_code, name) values ("TW","Taiwan")',
'insert into places_country (country_code, name) values ("TJ","Tajikistan")',
'insert into places_country (country_code, name) values ("TZ","Tanzania")',
'insert into places_country (country_code, name) values ("TH","Thailand")',
'insert into places_country (country_code, name) values ("TG","Togo")',
'insert into places_country (country_code, name) values ("TK","Tokelau")',
'insert into places_country (country_code, name) values ("TO","Tonga")',
'insert into places_country (country_code, name) values ("TT","Trinidad and Tobago")',
'insert into places_country (country_code, name) values ("TN","Tunisia")',
'insert into places_country (country_code, name) values ("TR","Turkey")',
'insert into places_country (country_code, name) values ("TM","Turkmenistan")',
'insert into places_country (country_code, name) values ("TC","Turks and Caicos Islands")',
'insert into places_country (country_code, name) values ("TV","Tuvalu")',
'insert into places_country (country_code, name) values ("UG","Uganda")',
'insert into places_country (country_code, name) values ("UA","Ukraine")',
'insert into places_country (country_code, name) values ("AE","United Arab Emirates")',
'insert into places_country (country_code, name) values ("GB","United Kingdom")',
'insert into places_country (country_code, name) values ("US","United States")',
'insert into places_country (country_code, name) values ("UM","United States Minor Outlying Islands")',
'insert into places_country (country_code, name) values ("UY","Uruguay")',
'insert into places_country (country_code, name) values ("VI","U.S. Virgin Islands")',
'insert into places_country (country_code, name) values ("UZ","Uzbekistan")',
'insert into places_country (country_code, name) values ("VU","Vanuatu")',
'insert into places_country (country_code, name) values ("VA","Vatican City")',
'insert into places_country (country_code, name) values ("VE","Venezuela")',
'insert into places_country (country_code, name) values ("VN","Vietnam")',
'insert into places_country (country_code, name) values ("WF","Wallis and Futuna")',
'insert into places_country (country_code, name) values ("EH","Western Sahara")',
'insert into places_country (country_code, name) values ("YE","Yemen")',
'insert into places_country (country_code, name) values ("ZM","Zambia")',
'insert into places_country (country_code, name) values ("ZW","Zimbabwe")',
                  ]
        sql_down = []
        super(CustomMigration, self).__init__(
            sql_up=sql_up, sql_down=sql_down
        )

migration = CustomMigration()
