# -*- coding: utf-8 -*-

from django.conf import settings
if settings.DATABASE_ENGINE == 'mysql':
    from dmigrations.mysql import migrations as m
elif settings.DATABASE_ENGINE == 'sqlite3':
    from dmigrations.sqlite3 import migrations as m

class CustomMigration(m.Migration):
    def __init__(self):
        sql_up = ['delete from places_country',
u'insert into places_country (country_code, name) values ("AF","Afghanistan")',
u'insert into places_country (country_code, name) values ("AX","Åland Islands")',
u'insert into places_country (country_code, name) values ("AL","Albania")',
u'insert into places_country (country_code, name) values ("DZ","Algeria")',
u'insert into places_country (country_code, name) values ("AS","American Samoa")',
u'insert into places_country (country_code, name) values ("AD","Andorra")',
u'insert into places_country (country_code, name) values ("AO","Angola")',
u'insert into places_country (country_code, name) values ("AI","Anguilla")',
u'insert into places_country (country_code, name) values ("AQ","Antarctica")',
u'insert into places_country (country_code, name) values ("AG","Antigua and Barbuda")',
u'insert into places_country (country_code, name) values ("AR","Argentina")',
u'insert into places_country (country_code, name) values ("AM","Armenia")',
u'insert into places_country (country_code, name) values ("AW","Aruba")',
u'insert into places_country (country_code, name) values ("AU","Australia")',
u'insert into places_country (country_code, name) values ("AT","Austria")',
u'insert into places_country (country_code, name) values ("AZ","Azerbaijan")',
u'insert into places_country (country_code, name) values ("BS","Bahamas")',
u'insert into places_country (country_code, name) values ("BH","Bahrain")',
u'insert into places_country (country_code, name) values ("BD","Bangladesh")',
u'insert into places_country (country_code, name) values ("BB","Barbados")',
u'insert into places_country (country_code, name) values ("BY","Belarus")',
u'insert into places_country (country_code, name) values ("BE","Belgium")',
u'insert into places_country (country_code, name) values ("BZ","Belize")',
u'insert into places_country (country_code, name) values ("BJ","Benin")',
u'insert into places_country (country_code, name) values ("BM","Bermuda")',
u'insert into places_country (country_code, name) values ("BT","Bhutan")',
u'insert into places_country (country_code, name) values ("BO","Bolivia")',
u'insert into places_country (country_code, name) values ("BA","Bosnia and Herzegovina")',
u'insert into places_country (country_code, name) values ("BW","Botswana")',
u'insert into places_country (country_code, name) values ("BV","Bouvet Island")',
u'insert into places_country (country_code, name) values ("BR","Brazil")',
u'insert into places_country (country_code, name) values ("IO","British Indian Ocean Territory")',
u'insert into places_country (country_code, name) values ("VG","British Virgin Islands")',
u'insert into places_country (country_code, name) values ("BN","Brunei")',
u'insert into places_country (country_code, name) values ("BG","Bulgaria")',
u'insert into places_country (country_code, name) values ("BF","Burkina Faso")',
u'insert into places_country (country_code, name) values ("BI","Burundi")',
u'insert into places_country (country_code, name) values ("KH","Cambodia")',
u'insert into places_country (country_code, name) values ("CM","Cameroon")',
u'insert into places_country (country_code, name) values ("CA","Canada")',
u'insert into places_country (country_code, name) values ("CV","Cape Verde")',
u'insert into places_country (country_code, name) values ("KY","Cayman Islands")',
u'insert into places_country (country_code, name) values ("CF","Central African Republic")',
u'insert into places_country (country_code, name) values ("TD","Chad")',
u'insert into places_country (country_code, name) values ("CL","Chile")',
u'insert into places_country (country_code, name) values ("CN","China")',
u'insert into places_country (country_code, name) values ("CX","Christmas Island")',
u'insert into places_country (country_code, name) values ("CC","Cocos (Keeling) Islands")',
u'insert into places_country (country_code, name) values ("CO","Colombia")',
u'insert into places_country (country_code, name) values ("KM","Comoros")',
u'insert into places_country (country_code, name) values ("CG","Congo")',
u'insert into places_country (country_code, name) values ("CK","Cook Islands")',
u'insert into places_country (country_code, name) values ("CR","Costa Rica")',
u'insert into places_country (country_code, name) values ("CI","Côte d\'Ivoire")',
u'insert into places_country (country_code, name) values ("HR","Croatia")',
u'insert into places_country (country_code, name) values ("CU","Cuba")',
u'insert into places_country (country_code, name) values ("CY","Cyprus")',
u'insert into places_country (country_code, name) values ("CZ","Czech Republic")',
u'insert into places_country (country_code, name) values ("CD","Democratic Republic of the Congo")',
u'insert into places_country (country_code, name) values ("DK","Denmark")',
u'insert into places_country (country_code, name) values ("DJ","Djibouti")',
u'insert into places_country (country_code, name) values ("DM","Dominica")',
u'insert into places_country (country_code, name) values ("DO","Dominican Republic")',
u'insert into places_country (country_code, name) values ("TL","East Timor")',
u'insert into places_country (country_code, name) values ("EC","Ecuador")',
u'insert into places_country (country_code, name) values ("EG","Egypt")',
u'insert into places_country (country_code, name) values ("SV","El Salvador")',
u'insert into places_country (country_code, name) values ("GQ","Equatorial Guinea")',
u'insert into places_country (country_code, name) values ("ER","Eritrea")',
u'insert into places_country (country_code, name) values ("EE","Estonia")',
u'insert into places_country (country_code, name) values ("ET","Ethiopia")',
u'insert into places_country (country_code, name) values ("FK","Falkland Islands")',
u'insert into places_country (country_code, name) values ("FO","Faroe Islands")',
u'insert into places_country (country_code, name) values ("FM","Federated States of Micronesia")',
u'insert into places_country (country_code, name) values ("FJ","Fiji")',
u'insert into places_country (country_code, name) values ("FI","Finland")',
u'insert into places_country (country_code, name) values ("FR","France")',
u'insert into places_country (country_code, name) values ("GF","French Guiana")',
u'insert into places_country (country_code, name) values ("PF","French Polynesia")',
u'insert into places_country (country_code, name) values ("TF","French Southern Territories")',
u'insert into places_country (country_code, name) values ("GA","Gabon")',
u'insert into places_country (country_code, name) values ("GM","Gambia")',
u'insert into places_country (country_code, name) values ("GE","Georgia")',
u'insert into places_country (country_code, name) values ("DE","Germany")',
u'insert into places_country (country_code, name) values ("GH","Ghana")',
u'insert into places_country (country_code, name) values ("GI","Gibraltar")',
u'insert into places_country (country_code, name) values ("GR","Greece")',
u'insert into places_country (country_code, name) values ("GL","Greenland")',
u'insert into places_country (country_code, name) values ("GD","Grenada")',
u'insert into places_country (country_code, name) values ("GG","Guernsey")',
u'insert into places_country (country_code, name) values ("GP","Guadeloupe")',
u'insert into places_country (country_code, name) values ("GU","Guam")',
u'insert into places_country (country_code, name) values ("GT","Guatemala")',
u'insert into places_country (country_code, name) values ("GW","Guinea-Bissau")',
u'insert into places_country (country_code, name) values ("GN","Guinea")',
u'insert into places_country (country_code, name) values ("GY","Guyana")',
u'insert into places_country (country_code, name) values ("HT","Haiti")',
u'insert into places_country (country_code, name) values ("HM","Heard Island and McDonald Islands")',
u'insert into places_country (country_code, name) values ("HN","Honduras")',
u'insert into places_country (country_code, name) values ("HK","Hong Kong")',
u'insert into places_country (country_code, name) values ("HU","Hungary")',
u'insert into places_country (country_code, name) values ("IS","Iceland")',
u'insert into places_country (country_code, name) values ("IN","India")',
u'insert into places_country (country_code, name) values ("ID","Indonesia")',
u'insert into places_country (country_code, name) values ("IR","Iran")',
u'insert into places_country (country_code, name) values ("IQ","Iraq")',
u'insert into places_country (country_code, name) values ("IE","Ireland")',
u'insert into places_country (country_code, name) values ("IL","Israel")',
u'insert into places_country (country_code, name) values ("IM","Isle of Man")',
u'insert into places_country (country_code, name) values ("IT","Italy")',
u'insert into places_country (country_code, name) values ("JE","Jersey")',
u'insert into places_country (country_code, name) values ("JM","Jamaica")',
u'insert into places_country (country_code, name) values ("JP","Japan")',
u'insert into places_country (country_code, name) values ("JO","Jordan")',
u'insert into places_country (country_code, name) values ("KZ","Kazakhstan")',
u'insert into places_country (country_code, name) values ("KE","Kenya")',
u'insert into places_country (country_code, name) values ("KI","Kiribati")',
u'insert into places_country (country_code, name) values ("KW","Kuwait")',
u'insert into places_country (country_code, name) values ("KG","Kyrgyzstan")',
u'insert into places_country (country_code, name) values ("LA","Laos")',
u'insert into places_country (country_code, name) values ("LV","Latvia")',
u'insert into places_country (country_code, name) values ("LB","Lebanon")',
u'insert into places_country (country_code, name) values ("LS","Lesotho")',
u'insert into places_country (country_code, name) values ("LR","Liberia")',
u'insert into places_country (country_code, name) values ("LY","Libya")',
u'insert into places_country (country_code, name) values ("LI","Liechtenstein")',
u'insert into places_country (country_code, name) values ("LT","Lithuania")',
u'insert into places_country (country_code, name) values ("LU","Luxembourg")',
u'insert into places_country (country_code, name) values ("MO","Macao")',
u'insert into places_country (country_code, name) values ("MG","Madagascar")',
u'insert into places_country (country_code, name) values ("MW","Malawi")',
u'insert into places_country (country_code, name) values ("MY","Malaysia")',
u'insert into places_country (country_code, name) values ("MV","Maldives")',
u'insert into places_country (country_code, name) values ("ML","Mali")',
u'insert into places_country (country_code, name) values ("MT","Malta")',
u'insert into places_country (country_code, name) values ("MH","Marshall Islands")',
u'insert into places_country (country_code, name) values ("MQ","Martinique")',
u'insert into places_country (country_code, name) values ("MR","Mauritania")',
u'insert into places_country (country_code, name) values ("MU","Mauritius")',
u'insert into places_country (country_code, name) values ("YT","Mayotte")',
u'insert into places_country (country_code, name) values ("MX","Mexico")',
u'insert into places_country (country_code, name) values ("MD","Moldova")',
u'insert into places_country (country_code, name) values ("MC","Monaco")',
u'insert into places_country (country_code, name) values ("MN","Mongolia")',
u'insert into places_country (country_code, name) values ("MS","Montserrat")',
u'insert into places_country (country_code, name) values ("MA","Morocco")',
u'insert into places_country (country_code, name) values ("MZ","Mozambique")',
u'insert into places_country (country_code, name) values ("MM","Myanmar")',
u'insert into places_country (country_code, name) values ("NA","Namibia")',
u'insert into places_country (country_code, name) values ("NR","Nauru")',
u'insert into places_country (country_code, name) values ("NP","Nepal")',
u'insert into places_country (country_code, name) values ("NL","Netherlands")',
u'insert into places_country (country_code, name) values ("AN","Netherlands Antilles")',
u'insert into places_country (country_code, name) values ("NC","New Caledonia")',
u'insert into places_country (country_code, name) values ("NZ","New Zealand")',
u'insert into places_country (country_code, name) values ("NI","Nicaragua")',
u'insert into places_country (country_code, name) values ("NG","Nigeria")',
u'insert into places_country (country_code, name) values ("NE","Niger")',
u'insert into places_country (country_code, name) values ("NU","Niue")',
u'insert into places_country (country_code, name) values ("NF","Norfolk Island")',
u'insert into places_country (country_code, name) values ("KP","North Korea")',
u'insert into places_country (country_code, name) values ("MP","Northern Mariana Islands")',
u'insert into places_country (country_code, name) values ("NO","Norway")',
u'insert into places_country (country_code, name) values ("OM","Oman")',
u'insert into places_country (country_code, name) values ("PK","Pakistan")',
u'insert into places_country (country_code, name) values ("PW","Palau")',
u'insert into places_country (country_code, name) values ("PS","Palestinian Territories")',
u'insert into places_country (country_code, name) values ("PA","Panama")',
u'insert into places_country (country_code, name) values ("PG","Papua New Guinea")',
u'insert into places_country (country_code, name) values ("PY","Paraguay")',
u'insert into places_country (country_code, name) values ("PE","Peru")',
u'insert into places_country (country_code, name) values ("PH","Philippines")',
u'insert into places_country (country_code, name) values ("PN","Pitcairn Islands")',
u'insert into places_country (country_code, name) values ("PL","Poland")',
u'insert into places_country (country_code, name) values ("PT","Portugal")',
u'insert into places_country (country_code, name) values ("PR","Puerto Rico")',
u'insert into places_country (country_code, name) values ("QA","Qatar")',
u'insert into places_country (country_code, name) values ("RE","Réunion")',
u'insert into places_country (country_code, name) values ("MK","Republic of Macedonia")',
u'insert into places_country (country_code, name) values ("RO","Romania")',
u'insert into places_country (country_code, name) values ("RU","Russia")',
u'insert into places_country (country_code, name) values ("RW","Rwanda")',
u'insert into places_country (country_code, name) values ("SH","Saint Helena")',
u'insert into places_country (country_code, name) values ("KN","Saint Kitts and Nevis")',
u'insert into places_country (country_code, name) values ("LC","Saint Lucia")',
u'insert into places_country (country_code, name) values ("PM","Saint-Pierre and Miquelon")',
u'insert into places_country (country_code, name) values ("VC","Saint Vincent and the Grenadines")',
u'insert into places_country (country_code, name) values ("WS","Samoa")',
u'insert into places_country (country_code, name) values ("SM","San Marino")',
u'insert into places_country (country_code, name) values ("ST","São Tomé and Príncipe")',
u'insert into places_country (country_code, name) values ("SA","Saudi Arabia")',
u'insert into places_country (country_code, name) values ("SN","Senegal")',
u'insert into places_country (country_code, name) values ("CS","Serbia and Montenegro")',
u'insert into places_country (country_code, name) values ("SC","Seychelles")',
u'insert into places_country (country_code, name) values ("SL","Sierra Leone")',
u'insert into places_country (country_code, name) values ("SG","Singapore")',
u'insert into places_country (country_code, name) values ("SK","Slovakia")',
u'insert into places_country (country_code, name) values ("SI","Slovenia")',
u'insert into places_country (country_code, name) values ("SB","Solomon Islands")',
u'insert into places_country (country_code, name) values ("SO","Somalia")',
u'insert into places_country (country_code, name) values ("ZA","South Africa")',
u'insert into places_country (country_code, name) values ("GS","South Georgia and the South Sandwich Islands")',
u'insert into places_country (country_code, name) values ("KR","South Korea")',
u'insert into places_country (country_code, name) values ("ES","Spain")',
u'insert into places_country (country_code, name) values ("LK","Sri Lanka")',
u'insert into places_country (country_code, name) values ("SD","Sudan")',
u'insert into places_country (country_code, name) values ("SR","Suriname")',
u'insert into places_country (country_code, name) values ("SJ","Svalbard")',
u'insert into places_country (country_code, name) values ("SZ","Swaziland")',
u'insert into places_country (country_code, name) values ("SE","Sweden")',
u'insert into places_country (country_code, name) values ("CH","Switzerland")',
u'insert into places_country (country_code, name) values ("SY","Syria")',
u'insert into places_country (country_code, name) values ("TW","Taiwan")',
u'insert into places_country (country_code, name) values ("TJ","Tajikistan")',
u'insert into places_country (country_code, name) values ("TZ","Tanzania")',
u'insert into places_country (country_code, name) values ("TH","Thailand")',
u'insert into places_country (country_code, name) values ("TG","Togo")',
u'insert into places_country (country_code, name) values ("TK","Tokelau")',
u'insert into places_country (country_code, name) values ("TO","Tonga")',
u'insert into places_country (country_code, name) values ("TT","Trinidad and Tobago")',
u'insert into places_country (country_code, name) values ("TN","Tunisia")',
u'insert into places_country (country_code, name) values ("TR","Turkey")',
u'insert into places_country (country_code, name) values ("TM","Turkmenistan")',
u'insert into places_country (country_code, name) values ("TC","Turks and Caicos Islands")',
u'insert into places_country (country_code, name) values ("TV","Tuvalu")',
u'insert into places_country (country_code, name) values ("UG","Uganda")',
u'insert into places_country (country_code, name) values ("UA","Ukraine")',
u'insert into places_country (country_code, name) values ("AE","United Arab Emirates")',
u'insert into places_country (country_code, name) values ("GB","United Kingdom")',
u'insert into places_country (country_code, name) values ("US","United States")',
u'insert into places_country (country_code, name) values ("UM","United States Minor Outlying Islands")',
u'insert into places_country (country_code, name) values ("UY","Uruguay")',
u'insert into places_country (country_code, name) values ("VI","U.S. Virgin Islands")',
u'insert into places_country (country_code, name) values ("UZ","Uzbekistan")',
u'insert into places_country (country_code, name) values ("VU","Vanuatu")',
u'insert into places_country (country_code, name) values ("VA","Vatican City")',
u'insert into places_country (country_code, name) values ("VE","Venezuela")',
u'insert into places_country (country_code, name) values ("VN","Vietnam")',
u'insert into places_country (country_code, name) values ("WF","Wallis and Futuna")',
u'insert into places_country (country_code, name) values ("EH","Western Sahara")',
u'insert into places_country (country_code, name) values ("YE","Yemen")',
u'insert into places_country (country_code, name) values ("ZM","Zambia")',
u'insert into places_country (country_code, name) values ("ZW","Zimbabwe")',
                  ]
        sql_down = []
        super(CustomMigration, self).__init__(
            sql_up=sql_up, sql_down=sql_down
        )

migration = CustomMigration()
